import os
import requests
import time
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
from github import Github

# ===== READ KEYS FROM ENVIRONMENT VARIABLES =====
# Keys are stored securely on Render, NOT in this file!
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO_NAME = os.getenv("REPO_NAME", "oprino21-lab/ai-coding-assistant")

# ===== AI FUNCTION =====
def ask_ai(prompt):
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://localhost:8000",
        "X-Title": "My AI Bot"
    }
    data = {
        "model": "deepseek/deepseek-r1:free",
        "messages": [
            {"role": "system", "content": "You are a coding assistant. Write clean, working code."},
            {"role": "user", "content": prompt}
        ],
        "max_tokens": 2000
    }
    response = requests.post(
        "https://openrouter.ai/api/v1/chat/completions",
        headers=headers,
        json=data
    )
    result = response.json()
    return result["choices"][0]["message"]["content"]

# ===== GITHUB FUNCTION =====
def create_github_pr(instruction, ai_code):
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(REPO_NAME)
    
    main_branch = repo.get_branch("main")
    branch_name = f"ai-feature-{int(time.time())}"
    repo.create_git_ref(f"refs/heads/{branch_name}", main_branch.commit.sha)
    
    repo.create_file(
        "ai-generated-code.txt",
        f"AI: {instruction[:50]}",
        ai_code,
        branch=branch_name
    )
    
    pr = repo.create_pull(
        title=f"AI: {instruction[:50]}",
        body=f"Generated by AI Assistant\n\nTask: {instruction}",
        head=branch_name,
        base="main"
    )
    return pr.html_url

# ===== TELEGRAM HANDLERS =====
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "🤖 AI Code Assistant Ready!\n\n"
        "Send me any coding task.\n"
        "Example: 'Add a login button to index.html'"
    )

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_message = update.message.text
    await update.message.reply_text("⏳ Processing... This takes 30-60 seconds")
    
    try:
        ai_response = ask_ai(f"Write code for this task: {user_message}")
        pr_url = create_github_pr(user_message, ai_response)
        
        await update.message.reply_text(
            f"✅ Done! Pull Request created:\n{pr_url}\n\n"
            "Open GitHub app to review and merge."
        )
    except Exception as e:
        await update.message.reply_text(f"❌ Error: {str(e)}")

# ===== START BOT =====
if __name__ == "__main__":
    app = Application.builder().token(TELEGRAM_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    print("🤖 Bot is running! Open Telegram and send a message.")
    app.run_polling()
